#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd `dirname ${DIR}`

GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build .

VERSION=`cat VERSION`

IMAGE="quay.io/bakins/tcp2stdout:v${VERSION}"

docker build -t ${IMAGE} .
docker push ${IMAGE}
